---
# oracle-jdk8, tomcat8

- hosts: localhost
  remote_user: root
#  pre_tasks:
#    - name: ensure registry directory exists
#      file: path={{registry_installed_dir}} state=directory

  roles:
    - apps/jdk
    - apps/tomcat
    - apps/maven
    - apps/intellij
    - apps/docker