---

- name: Download tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
           dest=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz 

- name: Extract tomcat
  command: /bin/tar xzf /tmp/apache-tomcat-{{tomcat_version}}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{tomcat_version}}

- name: Remove home directory symlink
  shell: rm -f /opt/tomcat removes=/opt/tomcat

- name: Create home directory symlink
  file: src=/opt/apache-tomcat-{{tomcat_version}} path=/opt/tomcat state=link
