- name: check Tomcat version {{tomcat_version}} already installed
  stat: 
    path: "{{registry_installed_dir}}/tomcat-{{tomcat_version}}"
  register: version

# block will not be executed if the version is already installed
- block:

    - name: download Tomcat
      get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
               dest=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz 

    - name: extract Tomcat
      command: tar xzf /tmp/apache-tomcat-{{tomcat_version}}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{tomcat_version}}
    
    - name: remove old Tomcat version
      file: path=/opt/tomcat state=absent

    - name: set new Tomcat version
      shell: mv /opt/apache-tomcat-{{tomcat_version}} /opt/tomcat
    
    #delete old file and create a new file with the current version
    - name: create registry file
      shell: rm -f {{registry_installed_dir}}/tomcat-* && touch {{registry_installed_dir}}/tomcat-{{tomcat_version}}

    - name: delete tmp files
      file: path=/tmp/apache-tomcat-{{tomcat_version}}.tar.gz state=absent

  when: not version.stat.exists or tomcat_force_install|default(false) or force_reinstall|default(false)