- name: add docker apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    update_cache: yes

- name: install docker
  apt:
    name: docker-engine

- name: add vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- service:
    name: docker
    enabled: yes

- name: get docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755